In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/cleaned_dataset.csv')

In [3]:
df.head()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,profit
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,23.176
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40,60.520
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28,39.664
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64,63.232
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72,40.336

In [7]:
df.shape

(50000, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
 13  profit            50000 non-null  float64
dtypes: float64(5), int64(5), object(4)
memory usage: 5.3+ MB

In [5]:
df.isnull().sum()

order_id            0
order_date          0
product_id          0
product_category    0
price               0
discount_percent    0
quantity_sold       0
customer_region     0
payment_method      0
rating              0
review_count        0
discounted_price    0
total_revenue       0
profit              0
dtype: int64

In [8]:
duplicates_count = df.duplicated().sum()
print("Number of duplicates ", duplicates_count)

Number of duplicates  0

In [9]:

df['order_date'] = pd.to_datetime(df['order_date'])

In [11]:
print( df['order_date'].dtype)

dtype('<M8[ns]')

In [12]:

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.strftime('%b')
df['day_name'] = df['order_date'].dt.day_name()

df[['order_date', 'year', 'month', 'day_name']].head(3)

  order_date  year month   day_name
0 2022-04-13  2022   Apr  Wednesday
1 2023-03-12  2023   Mar     Sunday
2 2022-09-28  2022   Sep  Wednesday

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import  plotly.graph_objects as go
import plotly.figure_factory as ff

In [16]:
df_plot = df.groupby('order_date')['total_revenue'].sum().reset_index().sort_values('order_date')

fig = px.line(df_plot, x='order_date', y='total_revenue', title='Total Revenue Over Time')
fig.update_xaxes(title_text='Order Date')
fig.update_yaxes(title_text='Total Revenue ($)')
fig.show()

In [17]:
df_plot = df.groupby('product_category')['total_revenue'].sum().reset_index().sort_values('total_revenue', ascending=True)

fig = px.bar(df_plot, x='total_revenue', y='product_category', orientation='h', title='Total Revenue by Product Category')
fig.update_xaxes(title_text='Total Revenue ($)')
fig.update_yaxes(title_text='Product Category')
fig.show()

In [18]:
df_plot = df.groupby('customer_region')['profit'].sum().reset_index().sort_values('profit', ascending=False)

fig = px.bar(df_plot, x='customer_region', y='profit', title='Total Profit by Customer Region')
fig.update_xaxes(title_text='Customer Region')
fig.update_yaxes(title_text='Total Profit ($)')
fig.show()

In [19]:
df_plot = df['payment_method'].value_counts().reset_index()
df_plot.columns = ['payment_method', 'count']

fig = px.pie(df_plot, names='payment_method', values='count', title='Payment Methods Distribution')
fig.show()

In [21]:
df_plot = df.groupby('product_category')['rating'].mean().reset_index().sort_values('rating', ascending=False)

fig = px.bar(df_plot, x='product_category', y='rating', title='Average Customer Rating by Category')
fig.update_xaxes(title_text='Product Category')
fig.update_yaxes(title_text='Average Rating (Out of 5)')
fig.show()

In [20]:
df_plot = df.groupby('month')['total_revenue'].sum().reset_index()

fig = px.bar(df_plot, x='month', y='total_revenue', title='Total Revenue by Month')
fig.update_xaxes(title_text='Month')
fig.update_yaxes(title_text='Total Revenue ($)')
fig.show()

In [22]:
df_plot = df.groupby('discount_percent')['quantity_sold'].sum().reset_index()

fig = px.scatter(df_plot, x='discount_percent', y='quantity_sold', title='Impact of Discount Percent on Quantity Sold')
fig.update_xaxes(title_text='Discount Percent (%)')
fig.update_yaxes(title_text='Total Quantity Sold')
fig.show()

In [23]:
df_plot = df.groupby(['year', 'customer_region'])['profit'].sum().reset_index()

fig = px.bar(df_plot, x='year', y='profit', color='customer_region', barmode='group', title='Yearly Profit by Customer Region')
fig.update_xaxes(title_text='Year')
fig.update_yaxes(title_text='Total Profit ($)')
fig.show()